FROM maven:3-jdk-8


RUN mkdir -p myproj-demo
# Add a volume pointing to /tmp
WORKDIR /myproj-demo
COPY . .
RUN [ "mvn", "verify", "clean", "--fail-never"]
RUN mvn package

# Add the application's jar to the container
ADD target/myproj-demo.jar myproj-demo.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","-Djsse.enableSNIExtension=false","/myproj-demo/myproj-demo.jar"]

# Make port 8012 available to the world outside this container
EXPOSE 8090
~
