# Start with a base image containing Java runtime
FROM openjdk:8



# Add a volume pointing to /tmp
WORKDIR /myproj-demo

FROM maven:3.8.4-eclipse-temurin-17 AS build
RUN mvn install

# Add the application's jar to the container
ADD target/myproj-demo.jar myproj-demo.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","-Djsse.enableSNIExtension=false","/myproj-demo/myproj-demo.jar"]

# Make port 8012 available to the world outside this container
EXPOSE 8090