#Active profile
server:
  port: 8090

spring:
  application:
    name: digilock-service-svc

logging:
  level:
    org.springframework.web.method.support: TRACE  # Set DEBUG level for method support package
    org.springframework.web.servlet: TRACE