apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dep
  namespace: myproj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: java-app
          image: 697886065243.dkr.ecr.ap-south-1.amazonaws.com/myimage:12
          ports:
            - containerPort: 8090

