apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dep
  namespace: myproj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: java-app
          image: 697886065243.dkr.ecr.ap-south-1.amazonaws.com/myimage:15
          ports:
            - containerPort: 8090
          env:
            # Define the environment variable
            - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
              # from the key name in the ConfigMap.
              valueFrom:
                configMapKeyRef:
                  name: myconfig           # The ConfigMap this value comes from.
                  key: player_initial_lives # The key to fetch.
            - name: ST_DBHOST
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: ST_DBHOST

