apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myproj
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ig-digi-lock/api/*
            pathType: Prefix		  # Assuming you want to match any path under /ig-digi-lock/api/
      backend:
        service:
          name: myapp-svc
          port:
            number: 8090