apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: myproj
spec:
  type: ClusterIP
  selector:
    app: myapp # Replace with the selector matching your pods
  ports:
    - protocol: TCP
      port: 8090 # Port exposed by the service internally
      targetPort: 8090
